-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 09:48:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shop` ;

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`UserFunction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`UserFunction` ;

CREATE TABLE IF NOT EXISTS `shop`.`UserFunction` (
  `idUserFunction` INT NOT NULL AUTO_INCREMENT,
  `nameUserFunction` VARCHAR(145) NULL,
  PRIMARY KEY (`idUserFunction`),
  UNIQUE INDEX `idUser_Function_UNIQUE` (`idUserFunction` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`User` ;

CREATE TABLE IF NOT EXISTS `shop`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nameUser` VARCHAR(145) NOT NULL,
  `surnameUser` VARCHAR(145) NOT NULL,
  `sexUser` TINYINT(1) NULL,
  `stNumberUser` INT NULL,
  `streetUser` VARCHAR(145) NOT NULL,
  `zipCodeUser` VARCHAR(45) NOT NULL,
  `cityUser` VARCHAR(145) NOT NULL,
  `telUser` INT NOT NULL,
  `emailUser` VARCHAR(255) NOT NULL,
  `passwordUser` VARCHAR(255) NULL,
  `UserFunction_idUserFunction` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  INDEX `fk_User_UserFunction_idx` (`UserFunction_idUserFunction` ASC),
  CONSTRAINT `fk_User_UserFunction`
    FOREIGN KEY (`UserFunction_idUserFunction`)
    REFERENCES `shop`.`UserFunction` (`idUserFunction`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `shop`.`PaymentMethod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`PaymentMethod` ;

CREATE TABLE IF NOT EXISTS `shop`.`PaymentMethod` (
  `idPaymentMethod` INT NOT NULL AUTO_INCREMENT,
  `namePaymentMethod` VARCHAR(145) NOT NULL,
  `activePaymentMethod` TINYINT(1) NULL,
  PRIMARY KEY (`idPaymentMethod`),
  UNIQUE INDEX `idPaymentMethod_UNIQUE` (`idPaymentMethod` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`ProductCat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`ProductCat` ;

CREATE TABLE IF NOT EXISTS `shop`.`ProductCat` (
  `idProductCat` INT NOT NULL AUTO_INCREMENT,
  `nameProductCat` VARCHAR(145) NOT NULL,
  `descProductCat` VARCHAR(145) NOT NULL,
  `createdDateProductCat` INT NOT NULL,
  `editDateProductCat` INT NULL,
  `reasonEditProductTable` VARCHAR(255) NULL,
  `statusProductCat` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`idProductCat`),
  UNIQUE INDEX `idProduct_Cat_UNIQUE` (`idProductCat` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`Client` ;

CREATE TABLE IF NOT EXISTS `shop`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nameClient` VARCHAR(45) NOT NULL,
  `surnameClient` VARCHAR(45) NOT NULL,
  `phoneClient` INT NOT NULL,
  `cityClient` VARCHAR(145) NOT NULL,
  `stNumberClient` INT NOT NULL,
  `streetClient` VARCHAR(145) NOT NULL,
  `zipCodeClient` VARCHAR(45) NOT NULL,
  `emailClient` VARCHAR(255) NULL,
  `statusClient` TINYINT(1) NULL,
  `createdDateClient` INT NOT NULL,
  `lastVisitClient` INT NOT NULL,
  `sexClient` TINYINT NULL,
  `footSizeClient` INT NOT NULL,
  `mostBuyed_idProductCat` INT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC),
  INDEX `fk_Client_Product_Cat1_idx` (`mostBuyed_idProductCat` ASC),
  CONSTRAINT `fk_Client_Product_Cat1`
    FOREIGN KEY (`mostBuyed_idProductCat`)
    REFERENCES `shop`.`ProductCat` (`idProductCat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`Ticket` ;

CREATE TABLE IF NOT EXISTS `shop`.`Ticket` (
  `idTicket` INT NOT NULL AUTO_INCREMENT,
  `dateticket` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `PaymentMethod_idPaymentMethod` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`idTicket`),
  UNIQUE INDEX `idTicket_UNIQUE` (`idTicket` ASC),
  INDEX `fk_Ticket_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Ticket_PaymentMethod1_idx` (`PaymentMethod_idPaymentMethod` ASC),
  INDEX `fk_Ticket_Client1_idx` (`Client_idClient` ASC),
  CONSTRAINT `fk_Ticket_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `shop`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ticket_PaymentMethod1`
    FOREIGN KEY (`PaymentMethod_idPaymentMethod`)
    REFERENCES `shop`.`PaymentMethod` (`idPaymentMethod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ticket_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `shop`.`Client` (`idClient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`Supplier` ;

CREATE TABLE IF NOT EXISTS `shop`.`Supplier` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `nameSupplier` VARCHAR(145) NOT NULL,
  `surnameSuppliser` VARCHAR(145) NOT NULL,
  `phoneSupplier` INT NOT NULL,
  `emailSupplier` VARCHAR(255) NOT NULL,
  `stNumberSupplier` INT NULL,
  `streetSupplier` VARCHAR(145) NOT NULL,
  `zipCodeSupplier` VARCHAR(45) NOT NULL,
  `citySupplier` VARCHAR(145) NOT NULL,
  `statusSupplier` TINYINT(1) NULL DEFAULT 1,
  `createdDateSupplier` INT NOT NULL,
  `lastBuyDateSupplier` INT NULL,
  PRIMARY KEY (`idSupplier`),
  UNIQUE INDEX `idSupplier_UNIQUE` (`idSupplier` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`SizeVariant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`SizeVariant` ;

CREATE TABLE IF NOT EXISTS `shop`.`SizeVariant` (
  `idSizeVariant` INT NOT NULL AUTO_INCREMENT,
  `sizeVariant` INT NOT NULL,
  PRIMARY KEY (`idSizeVariant`),
  UNIQUE INDEX `idSizeVariant_UNIQUE` (`idSizeVariant` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`ColorVarint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`ColorVarint` ;

CREATE TABLE IF NOT EXISTS `shop`.`ColorVarint` (
  `idColorVariant` INT NOT NULL AUTO_INCREMENT,
  `nameColorVariant` VARCHAR(145) NOT NULL,
  PRIMARY KEY (`idColorVariant`),
  UNIQUE INDEX `idSizeVariant_UNIQUE` (`idColorVariant` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`ProductVariant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`ProductVariant` ;

CREATE TABLE IF NOT EXISTS `shop`.`ProductVariant` (
  `idProductVariant` INT NOT NULL AUTO_INCREMENT,
  `nameProductVariant` VARCHAR(145) NULL,
  `descProductVariant` MEDIUMTEXT NULL,
  `SizeVariant_idSizeVariant` INT NOT NULL,
  `ColorVarint_idColorVariant` INT NOT NULL,
  PRIMARY KEY (`idProductVariant`),
  UNIQUE INDEX `idProductVariant_UNIQUE` (`idProductVariant` ASC),
  INDEX `fk_ProductVariant_SizeVariant1_idx` (`SizeVariant_idSizeVariant` ASC),
  INDEX `fk_ProductVariant_ColorVarint1_idx` (`ColorVarint_idColorVariant` ASC),
  CONSTRAINT `fk_ProductVariant_SizeVariant1`
    FOREIGN KEY (`SizeVariant_idSizeVariant`)
    REFERENCES `shop`.`SizeVariant` (`idSizeVariant`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ProductVariant_ColorVarint1`
    FOREIGN KEY (`ColorVarint_idColorVariant`)
    REFERENCES `shop`.`ColorVarint` (`idColorVariant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`Product` ;

CREATE TABLE IF NOT EXISTS `shop`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `nameProduct` VARCHAR(145) NOT NULL,
  `priceProduct` DOUBLE NOT NULL,
  `minStockProduct` INT NULL,
  `descProduct` MEDIUMTEXT NOT NULL,
  `priceBuyProduct` DOUBLE NOT NULL,
  `lastBuyDateProduct` INT NOT NULL,
  `createdDateProduct` INT NOT NULL,
  `barCodeProduct` INT NOT NULL,
  `statusProduct` TINYINT(1) NULL DEFAULT 1,
  `Supplier_idSupplier` INT NOT NULL,
  `ProductVariant_idProductVariant` INT NOT NULL,
  `Product_Cat_idProductCat` INT NOT NULL,
  PRIMARY KEY (`idProduct`),
  UNIQUE INDEX `idProduct_UNIQUE` (`idProduct` ASC),
  INDEX `fk_Product_Supplier1_idx` (`Supplier_idSupplier` ASC),
  INDEX `fk_Product_ProductVariant1_idx` (`ProductVariant_idProductVariant` ASC),
  UNIQUE INDEX `barCodeProduct_UNIQUE` (`barCodeProduct` ASC),
  INDEX `fk_Product_Product_Cat1_idx` (`Product_Cat_idProductCat` ASC),
  CONSTRAINT `fk_Product_Supplier1`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `shop`.`Supplier` (`idSupplier`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Product_ProductVariant1`
    FOREIGN KEY (`ProductVariant_idProductVariant`)
    REFERENCES `shop`.`ProductVariant` (`idProductVariant`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Product_Product_Cat1`
    FOREIGN KEY (`Product_Cat_idProductCat`)
    REFERENCES `shop`.`ProductCat` (`idProductCat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`ProductLeaving`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`ProductLeaving` ;

CREATE TABLE IF NOT EXISTS `shop`.`ProductLeaving` (
  `idProductLeaving` INT NOT NULL AUTO_INCREMENT,
  `qtyProductLeaving` VARCHAR(45) NULL,
  `Product_idProduct` INT NOT NULL,
  `Ticket_idTicket` INT NOT NULL,
  PRIMARY KEY (`idProductLeaving`),
  UNIQUE INDEX `idProductLeaving_UNIQUE` (`idProductLeaving` ASC),
  INDEX `fk_ProductLeaving_Product1_idx` (`Product_idProduct` ASC),
  INDEX `fk_ProductLeaving_Ticket1_idx` (`Ticket_idTicket` ASC),
  CONSTRAINT `fk_ProductLeaving_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `shop`.`Product` (`idProduct`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ProductLeaving_Ticket1`
    FOREIGN KEY (`Ticket_idTicket`)
    REFERENCES `shop`.`Ticket` (`idTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`ProductStock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`ProductStock` ;

CREATE TABLE IF NOT EXISTS `shop`.`ProductStock` (
  `idProductStock` INT NOT NULL AUTO_INCREMENT,
  `actionProductStock` TINYINT(2) NULL COMMENT '0 = ajout (retour client par ex.)\n1 = retrait (achat d\'un client par ex.)',
  `ProductLeaving_idProductLeaving` INT NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idProductStock`),
  UNIQUE INDEX `idProductStock_UNIQUE` (`idProductStock` ASC),
  INDEX `fk_ProductStock_ProductLeaving1_idx` (`ProductLeaving_idProductLeaving` ASC),
  INDEX `fk_ProductStock_Product1_idx` (`Product_idProduct` ASC),
  CONSTRAINT `fk_ProductStock_ProductLeaving1`
    FOREIGN KEY (`ProductLeaving_idProductLeaving`)
    REFERENCES `shop`.`ProductLeaving` (`idProductLeaving`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ProductStock_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `shop`.`Product` (`idProduct`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `shop`.`UserFunction`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`UserFunction` (`idUserFunction`, `nameUserFunction`) VALUES (1, 'Caissier');
INSERT INTO `shop`.`UserFunction` (`idUserFunction`, `nameUserFunction`) VALUES (2, 'Manager');
INSERT INTO `shop`.`UserFunction` (`idUserFunction`, `nameUserFunction`) VALUES (3, 'Comptable');
INSERT INTO `shop`.`UserFunction` (`idUserFunction`, `nameUserFunction`) VALUES (4, 'PDG');

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`User` (`idUser`, `nameUser`, `surnameUser`, `sexUser`, `stNumberUser`, `streetUser`, `zipCodeUser`, `cityUser`, `telUser`, `emailUser`, `passwordUser`, `UserFunction_idUserFunction`) VALUES (1, 'Doe', 'John', 0, 5, 'rue du chateau', '93000', 'Bobigny', 33600000001, 'john/doe@mymail.com', '$2y$12$QjSH496pcT5CEbzjD/vtVeH03tfHKFy36d4J0Ltp3lRtee9HDxY3K', 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`PaymentMethod`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`PaymentMethod` (`idPaymentMethod`, `namePaymentMethod`, `activePaymentMethod`) VALUES (1, 'Espèce', 1);
INSERT INTO `shop`.`PaymentMethod` (`idPaymentMethod`, `namePaymentMethod`, `activePaymentMethod`) VALUES (2, 'Chèque', 0);
INSERT INTO `shop`.`PaymentMethod` (`idPaymentMethod`, `namePaymentMethod`, `activePaymentMethod`) VALUES (3, 'CB', 1);
INSERT INTO `shop`.`PaymentMethod` (`idPaymentMethod`, `namePaymentMethod`, `activePaymentMethod`) VALUES (4, 'CBSC', 1);
INSERT INTO `shop`.`PaymentMethod` (`idPaymentMethod`, `namePaymentMethod`, `activePaymentMethod`) VALUES (5, 'PayPal', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`ProductCat`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`ProductCat` (`idProductCat`, `nameProductCat`, `descProductCat`, `createdDateProductCat`, `editDateProductCat`, `reasonEditProductTable`, `statusProductCat`) VALUES (1, 'Bottes', 'ceci ets une description de catégorie d\'articles', 1585638739 , NULL, NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`Client`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`Client` (`idClient`, `nameClient`, `surnameClient`, `phoneClient`, `cityClient`, `stNumberClient`, `streetClient`, `zipCodeClient`, `emailClient`, `statusClient`, `createdDateClient`, `lastVisitClient`, `sexClient`, `footSizeClient`, `mostBuyed_idProductCat`) VALUES (1, 'Smith', 'Jane', 33700000001, 'Paris', 12, 'place de la république', '75000', NULL, 1, 1585638739, 1585638739, 1, 36, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`Ticket`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`Ticket` (`idTicket`, `dateticket`, `User_idUser`, `PaymentMethod_idPaymentMethod`, `Client_idClient`) VALUES (1, 1585638739, 1, 1, 1);
INSERT INTO `shop`.`Ticket` (`idTicket`, `dateticket`, `User_idUser`, `PaymentMethod_idPaymentMethod`, `Client_idClient`) VALUES (2, 1585638739, 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`Supplier`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`Supplier` (`idSupplier`, `nameSupplier`, `surnameSuppliser`, `phoneSupplier`, `emailSupplier`, `stNumberSupplier`, `streetSupplier`, `zipCodeSupplier`, `citySupplier`, `statusSupplier`, `createdDateSupplier`, `lastBuyDateSupplier`) VALUES (1, 'Smith', 'Aaron', 33327000001, 'aaron.smith@supplier.com', 0, 'rue du moulin', '62300', 'Lens', 1, 1585638739, 1585638739);

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`SizeVariant`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`SizeVariant` (`idSizeVariant`, `sizeVariant`) VALUES (1, 35);
INSERT INTO `shop`.`SizeVariant` (`idSizeVariant`, `sizeVariant`) VALUES (2, 36);
INSERT INTO `shop`.`SizeVariant` (`idSizeVariant`, `sizeVariant`) VALUES (3, 37);
INSERT INTO `shop`.`SizeVariant` (`idSizeVariant`, `sizeVariant`) VALUES (4, 38);
INSERT INTO `shop`.`SizeVariant` (`idSizeVariant`, `sizeVariant`) VALUES (5, 39);
INSERT INTO `shop`.`SizeVariant` (`idSizeVariant`, `sizeVariant`) VALUES (6, 40);
INSERT INTO `shop`.`SizeVariant` (`idSizeVariant`, `sizeVariant`) VALUES (7, 42);
INSERT INTO `shop`.`SizeVariant` (`idSizeVariant`, `sizeVariant`) VALUES (8, 44);
INSERT INTO `shop`.`SizeVariant` (`idSizeVariant`, `sizeVariant`) VALUES (9, 46);
INSERT INTO `shop`.`SizeVariant` (`idSizeVariant`, `sizeVariant`) VALUES (10, 48);
INSERT INTO `shop`.`SizeVariant` (`idSizeVariant`, `sizeVariant`) VALUES (11, 50);
INSERT INTO `shop`.`SizeVariant` (`idSizeVariant`, `sizeVariant`) VALUES (12, 52);

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`ColorVarint`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`ColorVarint` (`idColorVariant`, `nameColorVariant`) VALUES (1, 'Rouge');
INSERT INTO `shop`.`ColorVarint` (`idColorVariant`, `nameColorVariant`) VALUES (2, 'Bleu');
INSERT INTO `shop`.`ColorVarint` (`idColorVariant`, `nameColorVariant`) VALUES (3, 'Jaune');

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`ProductVariant`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`ProductVariant` (`idProductVariant`, `nameProductVariant`, `descProductVariant`, `SizeVariant_idSizeVariant`, `ColorVarint_idColorVariant`) VALUES (1, NULL, NULL, 2, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`Product`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`Product` (`idProduct`, `nameProduct`, `priceProduct`, `minStockProduct`, `descProduct`, `priceBuyProduct`, `lastBuyDateProduct`, `createdDateProduct`, `barCodeProduct`, `statusProduct`, `Supplier_idSupplier`, `ProductVariant_idProductVariant`, `Product_Cat_idProductCat`) VALUES (1, 'botte léopard Zara', 50, 5, 'Les bottes léopard en vrai cuir de plastique', 25, 1585638739, 1585638739, 35268745620, 1, 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`ProductLeaving`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`ProductLeaving` (`idProductLeaving`, `qtyProductLeaving`, `Product_idProduct`, `Ticket_idTicket`) VALUES (1, '5', 1, 1);
INSERT INTO `shop`.`ProductLeaving` (`idProductLeaving`, `qtyProductLeaving`, `Product_idProduct`, `Ticket_idTicket`) VALUES (2, '4', 1, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`ProductStock`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`ProductStock` (`idProductStock`, `actionProductStock`, `ProductLeaving_idProductLeaving`, `Product_idProduct`) VALUES (1, 0, 1, 1);
INSERT INTO `shop`.`ProductStock` (`idProductStock`, `actionProductStock`, `ProductLeaving_idProductLeaving`, `Product_idProduct`) VALUES (2, 1, 2, 1);

COMMIT;

