-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 22:38:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mcdChaussure
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mcdChaussure` ;

-- -----------------------------------------------------
-- Schema mcdChaussure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mcdChaussure` DEFAULT CHARACTER SET utf8 ;
USE `mcdChaussure` ;

-- -----------------------------------------------------
-- Table `mcdChaussure`.`TypeUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`TypeUser` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`TypeUser` (
  `idTypeUser` INT NOT NULL AUTO_INCREMENT,
  `nameTypeUser` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTypeUser`),
  UNIQUE INDEX `idTypeUser_UNIQUE` (`idTypeUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`Bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`Bank` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`Bank` (
  `idBank` INT NOT NULL AUTO_INCREMENT,
  `nameBank` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idBank`),
  UNIQUE INDEX `idBank_UNIQUE` (`idBank` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`RegionDept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`RegionDept` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`RegionDept` (
  `idRegionDept` INT NOT NULL AUTO_INCREMENT,
  `numDep` VARCHAR(10) NOT NULL,
  `nameDep` VARCHAR(100) NOT NULL,
  `nameRegion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idRegionDept`),
  UNIQUE INDEX `idRegionDept_UNIQUE` (`idRegionDept` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`City` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`City` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `zipCodeCity` VARCHAR(45) NOT NULL,
  `nameCity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCity`),
  UNIQUE INDEX `idVille_UNIQUE` (`idCity` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`User` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nameUser` VARCHAR(255) NOT NULL,
  `surnameUser` VARCHAR(100) NOT NULL,
  `stNumberUser` VARCHAR(20) NULL,
  `stNameUser` VARCHAR(150) NOT NULL,
  `mailUser` VARCHAR(255) NULL,
  `phoneUser` VARCHAR(45) NULL,
  `countryUser` VARCHAR(100) NOT NULL,
  `status` TINYINT(1) NULL,
  `TypeUser_idTypeUser` INT NOT NULL,
  `RegionDept_idRegionDept` INT NOT NULL,
  `City_idCity` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  INDEX `fk_User_TypeUser_idx` (`TypeUser_idTypeUser` ASC),
  INDEX `fk_User_RegionDept1_idx` (`RegionDept_idRegionDept` ASC),
  INDEX `fk_User_City1_idx` (`City_idCity` ASC),
  CONSTRAINT `fk_User_TypeUser`
    FOREIGN KEY (`TypeUser_idTypeUser`)
    REFERENCES `mcdChaussure`.`TypeUser` (`idTypeUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_RegionDept1`
    FOREIGN KEY (`RegionDept_idRegionDept`)
    REFERENCES `mcdChaussure`.`RegionDept` (`idRegionDept`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_City1`
    FOREIGN KEY (`City_idCity`)
    REFERENCES `mcdChaussure`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`Product` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `nameProduct` VARCHAR(140) NOT NULL,
  `descProduct` MEDIUMTEXT NOT NULL,
  `priceHTProduct` DOUBLE NULL,
  `refProduct` VARCHAR(45) NOT NULL,
  `vipProduct` TINYINT(1) NULL,
  `noteProduct` DECIMAL(4,2) NULL,
  `statusProduct` TINYINT(1) NULL,
  PRIMARY KEY (`idProduct`),
  UNIQUE INDEX `idProduct_UNIQUE` (`idProduct` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`Entrepot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`Entrepot` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`Entrepot` (
  `idEntrepot` INT NOT NULL AUTO_INCREMENT,
  `nameEntepot` VARCHAR(100) NOT NULL,
  `qte` INT NULL,
  `status` TINYINT(1) NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idEntrepot`),
  UNIQUE INDEX `idEntrepot_UNIQUE` (`idEntrepot` ASC),
  INDEX `fk_Entrepot_Product1_idx` (`Product_idProduct` ASC),
  CONSTRAINT `fk_Entrepot_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mcdChaussure`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`Cart` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`Cart` (
  `idCart` INT NOT NULL AUTO_INCREMENT,
  `qte` INT NULL,
  `dateCart` DATETIME NOT NULL,
  `User_idUser` INT NOT NULL,
  `Entrepot_idEntrepot` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idCart`),
  UNIQUE INDEX `idCart_UNIQUE` (`idCart` ASC),
  INDEX `fk_Cart_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Cart_Entrepot1_idx` (`Entrepot_idEntrepot` ASC),
  INDEX `fk_Cart_Product1_idx` (`Product_idProduct` ASC),
  CONSTRAINT `fk_Cart_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mcdChaussure`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cart_Entrepot1`
    FOREIGN KEY (`Entrepot_idEntrepot`)
    REFERENCES `mcdChaussure`.`Entrepot` (`idEntrepot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cart_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mcdChaussure`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`SizeProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`SizeProduct` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`SizeProduct` (
  `idSizeProduct` INT NOT NULL AUTO_INCREMENT,
  `nameSizeProduct` VARCHAR(45) NOT NULL,
  `statusSizeProduct` TINYINT(1) NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idSizeProduct`),
  UNIQUE INDEX `idSize_UNIQUE` (`idSizeProduct` ASC),
  INDEX `fk_SizeProduct_Product1_idx` (`Product_idProduct` ASC),
  CONSTRAINT `fk_SizeProduct_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mcdChaussure`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`MaterialProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`MaterialProduct` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`MaterialProduct` (
  `idMaterialProduct` INT NOT NULL AUTO_INCREMENT,
  `nameMaterialProdcut` VARCHAR(45) NOT NULL,
  `statusMaterialProduct` TINYINT(1) NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idMaterialProduct`),
  UNIQUE INDEX `idMaterial_UNIQUE` (`idMaterialProduct` ASC),
  INDEX `fk_MaterialProduct_Product1_idx` (`Product_idProduct` ASC),
  CONSTRAINT `fk_MaterialProduct_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mcdChaussure`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`CatProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`CatProduct` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`CatProduct` (
  `idCatProduct` INT NOT NULL AUTO_INCREMENT,
  `nameCatProduct` VARCHAR(145) NOT NULL,
  `statusCatProduct` TINYINT(1) NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idCatProduct`),
  UNIQUE INDEX `idCatProduct_UNIQUE` (`idCatProduct` ASC),
  INDEX `fk_CatProduct_Product1_idx` (`Product_idProduct` ASC),
  CONSTRAINT `fk_CatProduct_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mcdChaussure`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`GenderProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`GenderProduct` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`GenderProduct` (
  `idGenderProduct` INT NOT NULL AUTO_INCREMENT,
  `nameGenderProduct` VARCHAR(45) NOT NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idGenderProduct`),
  UNIQUE INDEX `idGenderProduct_UNIQUE` (`idGenderProduct` ASC),
  INDEX `fk_GenderProduct_Product1_idx` (`Product_idProduct` ASC),
  CONSTRAINT `fk_GenderProduct_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mcdChaussure`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`ColorProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`ColorProduct` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`ColorProduct` (
  `idColorProduct` INT NOT NULL AUTO_INCREMENT,
  `nameColorProduct` VARCHAR(45) NOT NULL,
  `statusColorProduct` TINYINT(1) NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idColorProduct`),
  UNIQUE INDEX `idColorProduct_UNIQUE` (`idColorProduct` ASC),
  INDEX `fk_ColorProduct_Product1_idx` (`Product_idProduct` ASC),
  CONSTRAINT `fk_ColorProduct_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mcdChaussure`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`TvaProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`TvaProduct` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`TvaProduct` (
  `idTvaProduct` INT NOT NULL AUTO_INCREMENT,
  `nameTvaProduct` VARCHAR(45) NOT NULL,
  `valueTvaProduct` DECIMAL(5,2) NULL,
  `statusTvaProduct` VARCHAR(45) NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idTvaProduct`),
  UNIQUE INDEX `idTvaProduct_UNIQUE` (`idTvaProduct` ASC),
  INDEX `fk_TvaProduct_Product1_idx` (`Product_idProduct` ASC),
  CONSTRAINT `fk_TvaProduct_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mcdChaussure`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mcdChaussure`.`User_has_Bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mcdChaussure`.`User_has_Bank` ;

CREATE TABLE IF NOT EXISTS `mcdChaussure`.`User_has_Bank` (
  `User_idUser` INT NOT NULL,
  `Bank_idBank` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Bank_idBank`),
  INDEX `fk_User_has_Bank_Bank1_idx` (`Bank_idBank` ASC),
  INDEX `fk_User_has_Bank_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_User_has_Bank_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mcdChaussure`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Bank_Bank1`
    FOREIGN KEY (`Bank_idBank`)
    REFERENCES `mcdChaussure`.`Bank` (`idBank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
