-- MySQL Script generated by MySQL Workbench
-- Fri Apr 10 10:01:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projectImmo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projectImmo` ;

-- -----------------------------------------------------
-- Schema projectImmo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectImmo` DEFAULT CHARACTER SET utf8 ;
USE `projectImmo` ;

-- -----------------------------------------------------
-- Table `projectImmo`.`agence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectImmo`.`agence` ;

CREATE TABLE IF NOT EXISTS `projectImmo`.`agence` (
  `idagence` INT NOT NULL AUTO_INCREMENT,
  `adresseAgence` VARCHAR(145) NULL,
  `numRueAgence` INT NULL,
  `cpAgence` VARCHAR(20) NULL,
  `villeAgence` VARCHAR(140) NULL,
  PRIMARY KEY (`idagence`),
  UNIQUE INDEX `idagence_UNIQUE` (`idagence` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectImmo`.`prestation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectImmo`.`prestation` ;

CREATE TABLE IF NOT EXISTS `projectImmo`.`prestation` (
  `idprestation` INT NOT NULL AUTO_INCREMENT,
  `typePrestation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprestation`),
  UNIQUE INDEX `idprestation_UNIQUE` (`idprestation` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectImmo`.`siteOption`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectImmo`.`siteOption` ;

CREATE TABLE IF NOT EXISTS `projectImmo`.`siteOption` (
  `idsiteOption` INT NOT NULL AUTO_INCREMENT,
  `siteName` VARCHAR(140) NOT NULL,
  `imgUrl` TEXT NOT NULL,
  `headTitle` VARCHAR(140) NOT NULL,
  `headDesc` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`idsiteOption`),
  UNIQUE INDEX `idsiteOption_UNIQUE` (`idsiteOption` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectImmo`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectImmo`.`client` ;

CREATE TABLE IF NOT EXISTS `projectImmo`.`client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nomClient` VARCHAR(45) NOT NULL,
  `PrenomClient` VARCHAR(45) NOT NULL,
  `numRueClient` INT NULL,
  `nomRueClient` VARCHAR(140) NOT NULL,
  `cpClient` VARCHAR(20) NOT NULL,
  `villeClient` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectImmo`.`maison`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectImmo`.`maison` ;

CREATE TABLE IF NOT EXISTS `projectImmo`.`maison` (
  `idmaison` INT NOT NULL AUTO_INCREMENT,
  `nomMaison` VARCHAR(140) NOT NULL,
  `prixMaison` DOUBLE NOT NULL,
  `nbPiece` INT NOT NULL,
  `surfaceMaison` DECIMAL NOT NULL,
  `surfaceGlobal` DECIMAL NOT NULL,
  `commission` DOUBLE NOT NULL,
  `numRueMaison` INT NULL,
  `nomRueMaison` VARCHAR(140) NOT NULL,
  `cpMaison` VARCHAR(20) NOT NULL,
  `villeMaison` VARCHAR(140) NOT NULL,
  `prestation_idprestation` INT NOT NULL,
  `agence_idagence` INT NOT NULL,
  PRIMARY KEY (`idmaison`),
  UNIQUE INDEX `idmaison_UNIQUE` (`idmaison` ASC),
  INDEX `fk_maison_prestation_idx` (`prestation_idprestation` ASC),
  INDEX `fk_maison_agence1_idx` (`agence_idagence` ASC),
  CONSTRAINT `fk_maison_prestation`
    FOREIGN KEY (`prestation_idprestation`)
    REFERENCES `projectImmo`.`prestation` (`idprestation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maison_agence1`
    FOREIGN KEY (`agence_idagence`)
    REFERENCES `projectImmo`.`agence` (`idagence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectImmo`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectImmo`.`transaction` ;

CREATE TABLE IF NOT EXISTS `projectImmo`.`transaction` (
  `idtransaction` INT NOT NULL AUTO_INCREMENT,
  `dateTransaction` DATETIME NULL,
  `datePayment` DATETIME NULL,
  `transactioncol` VARCHAR(45) NULL,
  `maison_idmaison` INT NOT NULL,
  `client_idClient` INT NOT NULL,
  PRIMARY KEY (`idtransaction`),
  UNIQUE INDEX `idtransaction_UNIQUE` (`idtransaction` ASC),
  INDEX `fk_transaction_maison1_idx` (`maison_idmaison` ASC),
  INDEX `fk_transaction_client1_idx` (`client_idClient` ASC),
  CONSTRAINT `fk_transaction_maison1`
    FOREIGN KEY (`maison_idmaison`)
    REFERENCES `projectImmo`.`maison` (`idmaison`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_client1`
    FOREIGN KEY (`client_idClient`)
    REFERENCES `projectImmo`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
