-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 11:56:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema products
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `products` ;

-- -----------------------------------------------------
-- Schema products
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `products` DEFAULT CHARACTER SET utf8 ;
USE `products` ;

-- -----------------------------------------------------
-- Table `products`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products`.`Category` ;

CREATE TABLE IF NOT EXISTS `products`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `nomCat` VARCHAR(45) NOT NULL,
  `descCat` MEDIUMTEXT NOT NULL,
  `statusCat` TINYINT(1) NULL DEFAULT 1,
  `dateAddCat` INT NOT NULL,
  `dateEditCat` INT NULL,
  `reasonEditCat` MEDIUMTEXT NULL,
  PRIMARY KEY (`idCategory`),
  UNIQUE INDEX `idCategory_UNIQUE` (`idCategory` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products`.`Product` ;

CREATE TABLE IF NOT EXISTS `products`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `nomProduct` VARCHAR(45) NOT NULL,
  `prixProductHT` DOUBLE NULL,
  `descProduct` MEDIUMTEXT NOT NULL,
  `statusProduct` TINYINT(1) NULL DEFAULT 1,
  `dateAddProduct` INT NOT NULL,
  `dateEditProduct` INT NULL,
  `reasonEditProduct` MEDIUMTEXT NULL,
  `Category_idCategory` INT NOT NULL,
  PRIMARY KEY (`idProduct`, `Category_idCategory`),
  UNIQUE INDEX `idProduct_UNIQUE` (`idProduct` ASC),
  INDEX `fk_Product_Category_idx` (`Category_idCategory` ASC),
  CONSTRAINT `fk_Product_Category`
    FOREIGN KEY (`Category_idCategory`)
    REFERENCES `products`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `products`.`Category`
-- -----------------------------------------------------
START TRANSACTION;
USE `products`;
INSERT INTO `products`.`Category` (`idCategory`, `nomCat`, `descCat`, `statusCat`, `dateAddCat`, `dateEditCat`, `reasonEditCat`) VALUES (1, 'iPhones', 'La célèbre marque de téléphone ultra cher pour rien', 1, 1585569109, NULL, NULL);
INSERT INTO `products`.`Category` (`idCategory`, `nomCat`, `descCat`, `statusCat`, `dateAddCat`, `dateEditCat`, `reasonEditCat`) VALUES (2, 'Android', 'Google voit tout, Google controle tout', 1, 1585569109, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `products`.`Product`
-- -----------------------------------------------------
START TRANSACTION;
USE `products`;
INSERT INTO `products`.`Product` (`idProduct`, `nomProduct`, `prixProductHT`, `descProduct`, `statusProduct`, `dateAddProduct`, `dateEditProduct`, `reasonEditProduct`, `Category_idCategory`) VALUES (1, 'iPhone XR', 1500, 'Beaucoup trop cher pour toi regarde autre chose', 1, 1585569109, NULL, NULL, 1);
INSERT INTO `products`.`Product` (`idProduct`, `nomProduct`, `prixProductHT`, `descProduct`, `statusProduct`, `dateAddProduct`, `dateEditProduct`, `reasonEditProduct`, `Category_idCategory`) VALUES (2, 'Alcatel JaiPasDSous', 10, 'Voilà au moins avec ce telephone tu pourra jouer a snake', 1, 1585569109, NULL, NULL, 2);

COMMIT;

